/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CardRouteImport } from './routes/card'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IsraelRouteImport } from './routes/israel'
import { Route as MeRouteImport } from './routes/me'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MoneyRouteImport } from './routes/money'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as ProgrammeRouteImport } from './routes/programme'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReverifyRouteImport } from './routes/reverify'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TopupRouteImport } from './routes/topup'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as AdminAppsRouteImport } from './routes/admin/apps'
import { Route as AdminControlsRouteImport } from './routes/admin/controls'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminMembershipsRouteImport } from './routes/admin/memberships'
import { Route as AdminMoneyRouteImport } from './routes/admin/money'
import { Route as AdminPlacesRouteImport } from './routes/admin/places'
import { Route as AdminProgrammesRouteImport } from './routes/admin/programmes'
import { Route as AdminPromotionsRouteImport } from './routes/admin/promotions'
import { Route as AdminSimRouteImport } from './routes/admin/sim'
import { Route as BeforeYouFlyIndexRouteImport } from './routes/before-you-fly/index'
import { Route as BeforeYouFlyEsimRouteImport } from './routes/before-you-fly/esim'
import { Route as BeforeYouFlyInsuranceRouteImport } from './routes/before-you-fly/insurance'
import { Route as BenefitsIndexRouteImport } from './routes/benefits/index'
import { Route as BenefitsIdRouteImport } from './routes/benefits/$id'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as ExploreArmyRouteImport } from './routes/explore/army'
import { Route as ExploreBudgetRouteImport } from './routes/explore/budget'
import { Route as ExploreCommunityRouteImport } from './routes/explore/community'
import { Route as ExploreCostOfLivingRouteImport } from './routes/explore/cost-of-living'
import { Route as ExploreDocumentsRouteImport } from './routes/explore/documents'
import { Route as ExploreEventsRouteImport } from './routes/explore/events'
import { Route as ExploreFoodRouteImport } from './routes/explore/food'
import { Route as ExploreHealthRouteImport } from './routes/explore/health'
import { Route as ExploreHousingRouteImport } from './routes/explore/housing'
import { Route as ExploreLoneSoldierRouteImport } from './routes/explore/lone-soldier'
import { Route as ExploreMapsRouteImport } from './routes/explore/maps'
import { Route as ExploreMoneyPlannerRouteImport } from './routes/explore/money-planner'
import { Route as ExploreReserveRouteImport } from './routes/explore/reserve'
import { Route as ExploreRidesRouteImport } from './routes/explore/rides'
import { Route as ExploreShopsRouteImport } from './routes/explore/shops'
import { Route as ExploreTransitRouteImport } from './routes/explore/transit'
import { Route as ExploreUlpanRouteImport } from './routes/explore/ulpan'
import { Route as ExploreUniRouteImport } from './routes/explore/uni'
import { Route as ExploreUniFinderRouteImport } from './routes/explore/uni-finder'
import { Route as ExploreVisaRouteImport } from './routes/explore/visa'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesIdRouteImport } from './routes/guides/$id'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as ProgrammeIndexRouteImport } from './routes/programme.index'
import { Route as ProgrammeInboxRouteImport } from './routes/programme.inbox'
import { Route as ProgrammeInfoRouteImport } from './routes/programme.info'
import { Route as ProgrammeScheduleRouteImport } from './routes/programme.schedule'
import { Route as ProgrammeStaffRouteImport } from './routes/programme.staff'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesInsuranceRouteImport } from './routes/services/insurance'
import { Route as ServicesOffersRouteImport } from './routes/services/offers'
import { Route as SiddurIndexRouteImport } from './routes/siddur/index'
import { Route as SiddurIdRouteImport } from './routes/siddur/$id'
import { Route as SocialIndexRouteImport } from './routes/social/index'
import { Route as SocialConversationIdRouteImport } from './routes/social/$conversationId'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffCalendarRouteImport } from './routes/staff/calendar'
import { Route as StaffCommunicationsRouteImport } from './routes/staff/communications'
import { Route as StaffContentRouteImport } from './routes/staff/content'
import { Route as StaffOnboardingRouteImport } from './routes/staff/onboarding'
import { Route as StaffOverviewRouteImport } from './routes/staff/overview'
import { Route as StaffSettingsRouteImport } from './routes/staff/settings'
import { Route as StaffTeamRouteImport } from './routes/staff/team'
import { Route as WhatsOnIndexRouteImport } from './routes/whats-on.index'
import { Route as ApiAuthEmailWebhookRouteImport } from './routes/api/auth/email-webhook'
import { Route as ExploreEventIdRouteImport } from './routes/explore/event.$id'
import { Route as ExploreFitnessIndexRouteImport } from './routes/explore/fitness.index'
import { Route as ExploreFitnessIdRouteImport } from './routes/explore/fitness.$id'
import { Route as ExploreIdfIndexRouteImport } from './routes/explore/idf.index'
import { Route as ExploreIdfUnitIdRouteImport } from './routes/explore/idf.$unitId'
import { Route as ExploreMapIndexRouteImport } from './routes/explore/map.index'
import { Route as ExploreMapIdRouteImport } from './routes/explore/map.$id'
import { Route as ExploreServiceIdRouteImport } from './routes/explore/service.$id'
import { Route as ServicesEsimIndexRouteImport } from './routes/services/esim.index'
import { Route as ServicesEsimPlanIdRouteImport } from './routes/services/esim.$planId'
import { Route as ServicesEsimMineRouteImport } from './routes/services/esim.mine'
import { Route as StaffStudentsIndexRouteImport } from './routes/staff/students/index'
import { Route as StaffStudentsStudentIdRouteImport } from './routes/staff/students/$studentId'
import { Route as WhatsOnEventIdRouteImport } from './routes/whats-on.event.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicWebhooksAirwallexRouteImport } from './routes/api/public/webhooks/airwallex'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IsraelRoute = IsraelRouteImport.update({
  id: '/israel',
  path: '/israel',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyRoute = MoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeRoute = ProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReverifyRoute = ReverifyRouteImport.update({
  id: '/reverify',
  path: '/reverify',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TopupRoute = TopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAppsRoute = AdminAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminControlsRoute = AdminControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMoneyRoute = AdminMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlacesRoute = AdminPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProgrammesRoute = AdminProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSimRoute = AdminSimRouteImport.update({
  id: '/sim',
  path: '/sim',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BeforeYouFlyIndexRoute = BeforeYouFlyIndexRouteImport.update({
  id: '/before-you-fly/',
  path: '/before-you-fly/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeforeYouFlyEsimRoute = BeforeYouFlyEsimRouteImport.update({
  id: '/before-you-fly/esim',
  path: '/before-you-fly/esim',
  getParentRoute: () => rootRouteImport,
} as any)
const BeforeYouFlyInsuranceRoute = BeforeYouFlyInsuranceRouteImport.update({
  id: '/before-you-fly/insurance',
  path: '/before-you-fly/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsIndexRoute = BenefitsIndexRouteImport.update({
  id: '/benefits/',
  path: '/benefits/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsIdRoute = BenefitsIdRouteImport.update({
  id: '/benefits/$id',
  path: '/benefits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreArmyRoute = ExploreArmyRouteImport.update({
  id: '/explore/army',
  path: '/explore/army',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreBudgetRoute = ExploreBudgetRouteImport.update({
  id: '/explore/budget',
  path: '/explore/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCommunityRoute = ExploreCommunityRouteImport.update({
  id: '/explore/community',
  path: '/explore/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCostOfLivingRoute = ExploreCostOfLivingRouteImport.update({
  id: '/explore/cost-of-living',
  path: '/explore/cost-of-living',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreDocumentsRoute = ExploreDocumentsRouteImport.update({
  id: '/explore/documents',
  path: '/explore/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreEventsRoute = ExploreEventsRouteImport.update({
  id: '/explore/events',
  path: '/explore/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreFoodRoute = ExploreFoodRouteImport.update({
  id: '/explore/food',
  path: '/explore/food',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreHealthRoute = ExploreHealthRouteImport.update({
  id: '/explore/health',
  path: '/explore/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreHousingRoute = ExploreHousingRouteImport.update({
  id: '/explore/housing',
  path: '/explore/housing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreLoneSoldierRoute = ExploreLoneSoldierRouteImport.update({
  id: '/explore/lone-soldier',
  path: '/explore/lone-soldier',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreMapsRoute = ExploreMapsRouteImport.update({
  id: '/explore/maps',
  path: '/explore/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreMoneyPlannerRoute = ExploreMoneyPlannerRouteImport.update({
  id: '/explore/money-planner',
  path: '/explore/money-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreReserveRoute = ExploreReserveRouteImport.update({
  id: '/explore/reserve',
  path: '/explore/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRidesRoute = ExploreRidesRouteImport.update({
  id: '/explore/rides',
  path: '/explore/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreShopsRoute = ExploreShopsRouteImport.update({
  id: '/explore/shops',
  path: '/explore/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreTransitRoute = ExploreTransitRouteImport.update({
  id: '/explore/transit',
  path: '/explore/transit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreUlpanRoute = ExploreUlpanRouteImport.update({
  id: '/explore/ulpan',
  path: '/explore/ulpan',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreUniRoute = ExploreUniRouteImport.update({
  id: '/explore/uni',
  path: '/explore/uni',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreUniFinderRoute = ExploreUniFinderRouteImport.update({
  id: '/explore/uni-finder',
  path: '/explore/uni-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreVisaRoute = ExploreVisaRouteImport.update({
  id: '/explore/visa',
  path: '/explore/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIdRoute = GuidesIdRouteImport.update({
  id: '/guides/$id',
  path: '/guides/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeIndexRoute = ProgrammeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgrammeRoute,
} as any)
const ProgrammeInboxRoute = ProgrammeInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ProgrammeRoute,
} as any)
const ProgrammeInfoRoute = ProgrammeInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => ProgrammeRoute,
} as any)
const ProgrammeScheduleRoute = ProgrammeScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ProgrammeRoute,
} as any)
const ProgrammeStaffRoute = ProgrammeStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ProgrammeRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInsuranceRoute = ServicesInsuranceRouteImport.update({
  id: '/services/insurance',
  path: '/services/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOffersRoute = ServicesOffersRouteImport.update({
  id: '/services/offers',
  path: '/services/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const SiddurIndexRoute = SiddurIndexRouteImport.update({
  id: '/siddur/',
  path: '/siddur/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiddurIdRoute = SiddurIdRouteImport.update({
  id: '/siddur/$id',
  path: '/siddur/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialIndexRoute = SocialIndexRouteImport.update({
  id: '/social/',
  path: '/social/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialConversationIdRoute = SocialConversationIdRouteImport.update({
  id: '/social/$conversationId',
  path: '/social/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffCalendarRoute = StaffCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffCommunicationsRoute = StaffCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffContentRoute = StaffContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffOnboardingRoute = StaffOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffOverviewRoute = StaffOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffTeamRoute = StaffTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => StaffRouteRoute,
} as any)
const WhatsOnIndexRoute = WhatsOnIndexRouteImport.update({
  id: '/whats-on/',
  path: '/whats-on/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthEmailWebhookRoute = ApiAuthEmailWebhookRouteImport.update({
  id: '/api/auth/email-webhook',
  path: '/api/auth/email-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreEventIdRoute = ExploreEventIdRouteImport.update({
  id: '/explore/event/$id',
  path: '/explore/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreFitnessIndexRoute = ExploreFitnessIndexRouteImport.update({
  id: '/explore/fitness/',
  path: '/explore/fitness/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreFitnessIdRoute = ExploreFitnessIdRouteImport.update({
  id: '/explore/fitness/$id',
  path: '/explore/fitness/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIdfIndexRoute = ExploreIdfIndexRouteImport.update({
  id: '/explore/idf/',
  path: '/explore/idf/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIdfUnitIdRoute = ExploreIdfUnitIdRouteImport.update({
  id: '/explore/idf/$unitId',
  path: '/explore/idf/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreMapIndexRoute = ExploreMapIndexRouteImport.update({
  id: '/explore/map/',
  path: '/explore/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreMapIdRoute = ExploreMapIdRouteImport.update({
  id: '/explore/map/$id',
  path: '/explore/map/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreServiceIdRoute = ExploreServiceIdRouteImport.update({
  id: '/explore/service/$id',
  path: '/explore/service/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEsimIndexRoute = ServicesEsimIndexRouteImport.update({
  id: '/services/esim/',
  path: '/services/esim/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEsimPlanIdRoute = ServicesEsimPlanIdRouteImport.update({
  id: '/services/esim/$planId',
  path: '/services/esim/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEsimMineRoute = ServicesEsimMineRouteImport.update({
  id: '/services/esim/mine',
  path: '/services/esim/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStudentsIndexRoute = StaffStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffStudentsStudentIdRoute = StaffStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => StaffRouteRoute,
} as any)
const WhatsOnEventIdRoute = WhatsOnEventIdRouteImport.update({
  id: '/whats-on/event/$id',
  path: '/whats-on/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksAirwallexRoute =
  ApiPublicWebhooksAirwallexRouteImport.update({
    id: '/api/public/webhooks/airwallex',
    path: '/api/public/webhooks/airwallex',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/exchange': typeof ExchangeRoute
  '/help': typeof HelpRoute
  '/israel': typeof IsraelRoute
  '/me': typeof MeRoute
  '/membership': typeof MembershipRoute
  '/money': typeof MoneyRoute
  '/news': typeof NewsRoute
  '/passport': typeof PassportRoute
  '/programme': typeof ProgrammeRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/reverify': typeof ReverifyRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRoute
  '/topup': typeof TopupRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/apps': typeof AdminAppsRoute
  '/admin/controls': typeof AdminControlsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/money': typeof AdminMoneyRoute
  '/admin/places': typeof AdminPlacesRoute
  '/admin/programmes': typeof AdminProgrammesRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/sim': typeof AdminSimRoute
  '/before-you-fly/esim': typeof BeforeYouFlyEsimRoute
  '/before-you-fly/insurance': typeof BeforeYouFlyInsuranceRoute
  '/benefits/$id': typeof BenefitsIdRoute
  '/explore/army': typeof ExploreArmyRoute
  '/explore/budget': typeof ExploreBudgetRoute
  '/explore/community': typeof ExploreCommunityRoute
  '/explore/cost-of-living': typeof ExploreCostOfLivingRoute
  '/explore/documents': typeof ExploreDocumentsRoute
  '/explore/events': typeof ExploreEventsRoute
  '/explore/food': typeof ExploreFoodRoute
  '/explore/health': typeof ExploreHealthRoute
  '/explore/housing': typeof ExploreHousingRoute
  '/explore/lone-soldier': typeof ExploreLoneSoldierRoute
  '/explore/maps': typeof ExploreMapsRoute
  '/explore/money-planner': typeof ExploreMoneyPlannerRoute
  '/explore/reserve': typeof ExploreReserveRoute
  '/explore/rides': typeof ExploreRidesRoute
  '/explore/shops': typeof ExploreShopsRoute
  '/explore/transit': typeof ExploreTransitRoute
  '/explore/ulpan': typeof ExploreUlpanRoute
  '/explore/uni': typeof ExploreUniRoute
  '/explore/uni-finder': typeof ExploreUniFinderRoute
  '/explore/visa': typeof ExploreVisaRoute
  '/guides/$id': typeof GuidesIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/programme/inbox': typeof ProgrammeInboxRoute
  '/programme/info': typeof ProgrammeInfoRoute
  '/programme/schedule': typeof ProgrammeScheduleRoute
  '/programme/staff': typeof ProgrammeStaffRoute
  '/services/insurance': typeof ServicesInsuranceRoute
  '/services/offers': typeof ServicesOffersRoute
  '/siddur/$id': typeof SiddurIdRoute
  '/social/$conversationId': typeof SocialConversationIdRoute
  '/staff/calendar': typeof StaffCalendarRoute
  '/staff/communications': typeof StaffCommunicationsRoute
  '/staff/content': typeof StaffContentRoute
  '/staff/onboarding': typeof StaffOnboardingRoute
  '/staff/overview': typeof StaffOverviewRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/team': typeof StaffTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/before-you-fly/': typeof BeforeYouFlyIndexRoute
  '/benefits/': typeof BenefitsIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/programme/': typeof ProgrammeIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/siddur/': typeof SiddurIndexRoute
  '/social/': typeof SocialIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/whats-on/': typeof WhatsOnIndexRoute
  '/api/auth/email-webhook': typeof ApiAuthEmailWebhookRoute
  '/explore/event/$id': typeof ExploreEventIdRoute
  '/explore/fitness/$id': typeof ExploreFitnessIdRoute
  '/explore/idf/$unitId': typeof ExploreIdfUnitIdRoute
  '/explore/map/$id': typeof ExploreMapIdRoute
  '/explore/service/$id': typeof ExploreServiceIdRoute
  '/services/esim/$planId': typeof ServicesEsimPlanIdRoute
  '/services/esim/mine': typeof ServicesEsimMineRoute
  '/staff/students/$studentId': typeof StaffStudentsStudentIdRoute
  '/whats-on/event/$id': typeof WhatsOnEventIdRoute
  '/explore/fitness/': typeof ExploreFitnessIndexRoute
  '/explore/idf/': typeof ExploreIdfIndexRoute
  '/explore/map/': typeof ExploreMapIndexRoute
  '/services/esim/': typeof ServicesEsimIndexRoute
  '/staff/students/': typeof StaffStudentsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/webhooks/airwallex': typeof ApiPublicWebhooksAirwallexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/exchange': typeof ExchangeRoute
  '/help': typeof HelpRoute
  '/israel': typeof IsraelRoute
  '/me': typeof MeRoute
  '/membership': typeof MembershipRoute
  '/money': typeof MoneyRoute
  '/news': typeof NewsRoute
  '/passport': typeof PassportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reverify': typeof ReverifyRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRoute
  '/topup': typeof TopupRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/apps': typeof AdminAppsRoute
  '/admin/controls': typeof AdminControlsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/money': typeof AdminMoneyRoute
  '/admin/places': typeof AdminPlacesRoute
  '/admin/programmes': typeof AdminProgrammesRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/sim': typeof AdminSimRoute
  '/before-you-fly/esim': typeof BeforeYouFlyEsimRoute
  '/before-you-fly/insurance': typeof BeforeYouFlyInsuranceRoute
  '/benefits/$id': typeof BenefitsIdRoute
  '/explore/army': typeof ExploreArmyRoute
  '/explore/budget': typeof ExploreBudgetRoute
  '/explore/community': typeof ExploreCommunityRoute
  '/explore/cost-of-living': typeof ExploreCostOfLivingRoute
  '/explore/documents': typeof ExploreDocumentsRoute
  '/explore/events': typeof ExploreEventsRoute
  '/explore/food': typeof ExploreFoodRoute
  '/explore/health': typeof ExploreHealthRoute
  '/explore/housing': typeof ExploreHousingRoute
  '/explore/lone-soldier': typeof ExploreLoneSoldierRoute
  '/explore/maps': typeof ExploreMapsRoute
  '/explore/money-planner': typeof ExploreMoneyPlannerRoute
  '/explore/reserve': typeof ExploreReserveRoute
  '/explore/rides': typeof ExploreRidesRoute
  '/explore/shops': typeof ExploreShopsRoute
  '/explore/transit': typeof ExploreTransitRoute
  '/explore/ulpan': typeof ExploreUlpanRoute
  '/explore/uni': typeof ExploreUniRoute
  '/explore/uni-finder': typeof ExploreUniFinderRoute
  '/explore/visa': typeof ExploreVisaRoute
  '/guides/$id': typeof GuidesIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/programme/inbox': typeof ProgrammeInboxRoute
  '/programme/info': typeof ProgrammeInfoRoute
  '/programme/schedule': typeof ProgrammeScheduleRoute
  '/programme/staff': typeof ProgrammeStaffRoute
  '/services/insurance': typeof ServicesInsuranceRoute
  '/services/offers': typeof ServicesOffersRoute
  '/siddur/$id': typeof SiddurIdRoute
  '/social/$conversationId': typeof SocialConversationIdRoute
  '/staff/calendar': typeof StaffCalendarRoute
  '/staff/communications': typeof StaffCommunicationsRoute
  '/staff/content': typeof StaffContentRoute
  '/staff/onboarding': typeof StaffOnboardingRoute
  '/staff/overview': typeof StaffOverviewRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/team': typeof StaffTeamRoute
  '/admin': typeof AdminIndexRoute
  '/before-you-fly': typeof BeforeYouFlyIndexRoute
  '/benefits': typeof BenefitsIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/programme': typeof ProgrammeIndexRoute
  '/services': typeof ServicesIndexRoute
  '/siddur': typeof SiddurIndexRoute
  '/social': typeof SocialIndexRoute
  '/staff': typeof StaffIndexRoute
  '/whats-on': typeof WhatsOnIndexRoute
  '/api/auth/email-webhook': typeof ApiAuthEmailWebhookRoute
  '/explore/event/$id': typeof ExploreEventIdRoute
  '/explore/fitness/$id': typeof ExploreFitnessIdRoute
  '/explore/idf/$unitId': typeof ExploreIdfUnitIdRoute
  '/explore/map/$id': typeof ExploreMapIdRoute
  '/explore/service/$id': typeof ExploreServiceIdRoute
  '/services/esim/$planId': typeof ServicesEsimPlanIdRoute
  '/services/esim/mine': typeof ServicesEsimMineRoute
  '/staff/students/$studentId': typeof StaffStudentsStudentIdRoute
  '/whats-on/event/$id': typeof WhatsOnEventIdRoute
  '/explore/fitness': typeof ExploreFitnessIndexRoute
  '/explore/idf': typeof ExploreIdfIndexRoute
  '/explore/map': typeof ExploreMapIndexRoute
  '/services/esim': typeof ServicesEsimIndexRoute
  '/staff/students': typeof StaffStudentsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/webhooks/airwallex': typeof ApiPublicWebhooksAirwallexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/exchange': typeof ExchangeRoute
  '/help': typeof HelpRoute
  '/israel': typeof IsraelRoute
  '/me': typeof MeRoute
  '/membership': typeof MembershipRoute
  '/money': typeof MoneyRoute
  '/news': typeof NewsRoute
  '/passport': typeof PassportRoute
  '/programme': typeof ProgrammeRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/reverify': typeof ReverifyRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRoute
  '/topup': typeof TopupRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/apps': typeof AdminAppsRoute
  '/admin/controls': typeof AdminControlsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/money': typeof AdminMoneyRoute
  '/admin/places': typeof AdminPlacesRoute
  '/admin/programmes': typeof AdminProgrammesRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/sim': typeof AdminSimRoute
  '/before-you-fly/esim': typeof BeforeYouFlyEsimRoute
  '/before-you-fly/insurance': typeof BeforeYouFlyInsuranceRoute
  '/benefits/$id': typeof BenefitsIdRoute
  '/explore/army': typeof ExploreArmyRoute
  '/explore/budget': typeof ExploreBudgetRoute
  '/explore/community': typeof ExploreCommunityRoute
  '/explore/cost-of-living': typeof ExploreCostOfLivingRoute
  '/explore/documents': typeof ExploreDocumentsRoute
  '/explore/events': typeof ExploreEventsRoute
  '/explore/food': typeof ExploreFoodRoute
  '/explore/health': typeof ExploreHealthRoute
  '/explore/housing': typeof ExploreHousingRoute
  '/explore/lone-soldier': typeof ExploreLoneSoldierRoute
  '/explore/maps': typeof ExploreMapsRoute
  '/explore/money-planner': typeof ExploreMoneyPlannerRoute
  '/explore/reserve': typeof ExploreReserveRoute
  '/explore/rides': typeof ExploreRidesRoute
  '/explore/shops': typeof ExploreShopsRoute
  '/explore/transit': typeof ExploreTransitRoute
  '/explore/ulpan': typeof ExploreUlpanRoute
  '/explore/uni': typeof ExploreUniRoute
  '/explore/uni-finder': typeof ExploreUniFinderRoute
  '/explore/visa': typeof ExploreVisaRoute
  '/guides/$id': typeof GuidesIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/programme/inbox': typeof ProgrammeInboxRoute
  '/programme/info': typeof ProgrammeInfoRoute
  '/programme/schedule': typeof ProgrammeScheduleRoute
  '/programme/staff': typeof ProgrammeStaffRoute
  '/services/insurance': typeof ServicesInsuranceRoute
  '/services/offers': typeof ServicesOffersRoute
  '/siddur/$id': typeof SiddurIdRoute
  '/social/$conversationId': typeof SocialConversationIdRoute
  '/staff/calendar': typeof StaffCalendarRoute
  '/staff/communications': typeof StaffCommunicationsRoute
  '/staff/content': typeof StaffContentRoute
  '/staff/onboarding': typeof StaffOnboardingRoute
  '/staff/overview': typeof StaffOverviewRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/team': typeof StaffTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/before-you-fly/': typeof BeforeYouFlyIndexRoute
  '/benefits/': typeof BenefitsIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/programme/': typeof ProgrammeIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/siddur/': typeof SiddurIndexRoute
  '/social/': typeof SocialIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/whats-on/': typeof WhatsOnIndexRoute
  '/api/auth/email-webhook': typeof ApiAuthEmailWebhookRoute
  '/explore/event/$id': typeof ExploreEventIdRoute
  '/explore/fitness/$id': typeof ExploreFitnessIdRoute
  '/explore/idf/$unitId': typeof ExploreIdfUnitIdRoute
  '/explore/map/$id': typeof ExploreMapIdRoute
  '/explore/service/$id': typeof ExploreServiceIdRoute
  '/services/esim/$planId': typeof ServicesEsimPlanIdRoute
  '/services/esim/mine': typeof ServicesEsimMineRoute
  '/staff/students/$studentId': typeof StaffStudentsStudentIdRoute
  '/whats-on/event/$id': typeof WhatsOnEventIdRoute
  '/explore/fitness/': typeof ExploreFitnessIndexRoute
  '/explore/idf/': typeof ExploreIdfIndexRoute
  '/explore/map/': typeof ExploreMapIndexRoute
  '/services/esim/': typeof ServicesEsimIndexRoute
  '/staff/students/': typeof StaffStudentsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/webhooks/airwallex': typeof ApiPublicWebhooksAirwallexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/staff'
    | '/activity'
    | '/auth'
    | '/card'
    | '/exchange'
    | '/help'
    | '/israel'
    | '/me'
    | '/membership'
    | '/money'
    | '/news'
    | '/passport'
    | '/programme'
    | '/reset-password'
    | '/reverify'
    | '/settings'
    | '/setup'
    | '/sitemap.xml'
    | '/terms'
    | '/tickets'
    | '/topup'
    | '/verify'
    | '/wallet'
    | '/welcome'
    | '/admin/accounts'
    | '/admin/apps'
    | '/admin/controls'
    | '/admin/events'
    | '/admin/memberships'
    | '/admin/money'
    | '/admin/places'
    | '/admin/programmes'
    | '/admin/promotions'
    | '/admin/sim'
    | '/before-you-fly/esim'
    | '/before-you-fly/insurance'
    | '/benefits/$id'
    | '/explore/army'
    | '/explore/budget'
    | '/explore/community'
    | '/explore/cost-of-living'
    | '/explore/documents'
    | '/explore/events'
    | '/explore/food'
    | '/explore/health'
    | '/explore/housing'
    | '/explore/lone-soldier'
    | '/explore/maps'
    | '/explore/money-planner'
    | '/explore/reserve'
    | '/explore/rides'
    | '/explore/shops'
    | '/explore/transit'
    | '/explore/ulpan'
    | '/explore/uni'
    | '/explore/uni-finder'
    | '/explore/visa'
    | '/guides/$id'
    | '/join/$code'
    | '/programme/inbox'
    | '/programme/info'
    | '/programme/schedule'
    | '/programme/staff'
    | '/services/insurance'
    | '/services/offers'
    | '/siddur/$id'
    | '/social/$conversationId'
    | '/staff/calendar'
    | '/staff/communications'
    | '/staff/content'
    | '/staff/onboarding'
    | '/staff/overview'
    | '/staff/settings'
    | '/staff/team'
    | '/admin/'
    | '/before-you-fly/'
    | '/benefits/'
    | '/explore/'
    | '/guides/'
    | '/programme/'
    | '/services/'
    | '/siddur/'
    | '/social/'
    | '/staff/'
    | '/whats-on/'
    | '/api/auth/email-webhook'
    | '/explore/event/$id'
    | '/explore/fitness/$id'
    | '/explore/idf/$unitId'
    | '/explore/map/$id'
    | '/explore/service/$id'
    | '/services/esim/$planId'
    | '/services/esim/mine'
    | '/staff/students/$studentId'
    | '/whats-on/event/$id'
    | '/explore/fitness/'
    | '/explore/idf/'
    | '/explore/map/'
    | '/services/esim/'
    | '/staff/students/'
    | '/api/public/payments/webhook'
    | '/api/public/webhooks/airwallex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/auth'
    | '/card'
    | '/exchange'
    | '/help'
    | '/israel'
    | '/me'
    | '/membership'
    | '/money'
    | '/news'
    | '/passport'
    | '/reset-password'
    | '/reverify'
    | '/settings'
    | '/setup'
    | '/sitemap.xml'
    | '/terms'
    | '/tickets'
    | '/topup'
    | '/verify'
    | '/wallet'
    | '/welcome'
    | '/admin/accounts'
    | '/admin/apps'
    | '/admin/controls'
    | '/admin/events'
    | '/admin/memberships'
    | '/admin/money'
    | '/admin/places'
    | '/admin/programmes'
    | '/admin/promotions'
    | '/admin/sim'
    | '/before-you-fly/esim'
    | '/before-you-fly/insurance'
    | '/benefits/$id'
    | '/explore/army'
    | '/explore/budget'
    | '/explore/community'
    | '/explore/cost-of-living'
    | '/explore/documents'
    | '/explore/events'
    | '/explore/food'
    | '/explore/health'
    | '/explore/housing'
    | '/explore/lone-soldier'
    | '/explore/maps'
    | '/explore/money-planner'
    | '/explore/reserve'
    | '/explore/rides'
    | '/explore/shops'
    | '/explore/transit'
    | '/explore/ulpan'
    | '/explore/uni'
    | '/explore/uni-finder'
    | '/explore/visa'
    | '/guides/$id'
    | '/join/$code'
    | '/programme/inbox'
    | '/programme/info'
    | '/programme/schedule'
    | '/programme/staff'
    | '/services/insurance'
    | '/services/offers'
    | '/siddur/$id'
    | '/social/$conversationId'
    | '/staff/calendar'
    | '/staff/communications'
    | '/staff/content'
    | '/staff/onboarding'
    | '/staff/overview'
    | '/staff/settings'
    | '/staff/team'
    | '/admin'
    | '/before-you-fly'
    | '/benefits'
    | '/explore'
    | '/guides'
    | '/programme'
    | '/services'
    | '/siddur'
    | '/social'
    | '/staff'
    | '/whats-on'
    | '/api/auth/email-webhook'
    | '/explore/event/$id'
    | '/explore/fitness/$id'
    | '/explore/idf/$unitId'
    | '/explore/map/$id'
    | '/explore/service/$id'
    | '/services/esim/$planId'
    | '/services/esim/mine'
    | '/staff/students/$studentId'
    | '/whats-on/event/$id'
    | '/explore/fitness'
    | '/explore/idf'
    | '/explore/map'
    | '/services/esim'
    | '/staff/students'
    | '/api/public/payments/webhook'
    | '/api/public/webhooks/airwallex'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/staff'
    | '/activity'
    | '/auth'
    | '/card'
    | '/exchange'
    | '/help'
    | '/israel'
    | '/me'
    | '/membership'
    | '/money'
    | '/news'
    | '/passport'
    | '/programme'
    | '/reset-password'
    | '/reverify'
    | '/settings'
    | '/setup'
    | '/sitemap.xml'
    | '/terms'
    | '/tickets'
    | '/topup'
    | '/verify'
    | '/wallet'
    | '/welcome'
    | '/admin/accounts'
    | '/admin/apps'
    | '/admin/controls'
    | '/admin/events'
    | '/admin/memberships'
    | '/admin/money'
    | '/admin/places'
    | '/admin/programmes'
    | '/admin/promotions'
    | '/admin/sim'
    | '/before-you-fly/esim'
    | '/before-you-fly/insurance'
    | '/benefits/$id'
    | '/explore/army'
    | '/explore/budget'
    | '/explore/community'
    | '/explore/cost-of-living'
    | '/explore/documents'
    | '/explore/events'
    | '/explore/food'
    | '/explore/health'
    | '/explore/housing'
    | '/explore/lone-soldier'
    | '/explore/maps'
    | '/explore/money-planner'
    | '/explore/reserve'
    | '/explore/rides'
    | '/explore/shops'
    | '/explore/transit'
    | '/explore/ulpan'
    | '/explore/uni'
    | '/explore/uni-finder'
    | '/explore/visa'
    | '/guides/$id'
    | '/join/$code'
    | '/programme/inbox'
    | '/programme/info'
    | '/programme/schedule'
    | '/programme/staff'
    | '/services/insurance'
    | '/services/offers'
    | '/siddur/$id'
    | '/social/$conversationId'
    | '/staff/calendar'
    | '/staff/communications'
    | '/staff/content'
    | '/staff/onboarding'
    | '/staff/overview'
    | '/staff/settings'
    | '/staff/team'
    | '/admin/'
    | '/before-you-fly/'
    | '/benefits/'
    | '/explore/'
    | '/guides/'
    | '/programme/'
    | '/services/'
    | '/siddur/'
    | '/social/'
    | '/staff/'
    | '/whats-on/'
    | '/api/auth/email-webhook'
    | '/explore/event/$id'
    | '/explore/fitness/$id'
    | '/explore/idf/$unitId'
    | '/explore/map/$id'
    | '/explore/service/$id'
    | '/services/esim/$planId'
    | '/services/esim/mine'
    | '/staff/students/$studentId'
    | '/whats-on/event/$id'
    | '/explore/fitness/'
    | '/explore/idf/'
    | '/explore/map/'
    | '/services/esim/'
    | '/staff/students/'
    | '/api/public/payments/webhook'
    | '/api/public/webhooks/airwallex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  ActivityRoute: typeof ActivityRoute
  AuthRoute: typeof AuthRoute
  CardRoute: typeof CardRoute
  ExchangeRoute: typeof ExchangeRoute
  HelpRoute: typeof HelpRoute
  IsraelRoute: typeof IsraelRoute
  MeRoute: typeof MeRoute
  MembershipRoute: typeof MembershipRoute
  MoneyRoute: typeof MoneyRoute
  NewsRoute: typeof NewsRoute
  PassportRoute: typeof PassportRoute
  ProgrammeRoute: typeof ProgrammeRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReverifyRoute: typeof ReverifyRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TicketsRoute: typeof TicketsRoute
  TopupRoute: typeof TopupRoute
  VerifyRoute: typeof VerifyRoute
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
  BeforeYouFlyEsimRoute: typeof BeforeYouFlyEsimRoute
  BeforeYouFlyInsuranceRoute: typeof BeforeYouFlyInsuranceRoute
  BenefitsIdRoute: typeof BenefitsIdRoute
  ExploreArmyRoute: typeof ExploreArmyRoute
  ExploreBudgetRoute: typeof ExploreBudgetRoute
  ExploreCommunityRoute: typeof ExploreCommunityRoute
  ExploreCostOfLivingRoute: typeof ExploreCostOfLivingRoute
  ExploreDocumentsRoute: typeof ExploreDocumentsRoute
  ExploreEventsRoute: typeof ExploreEventsRoute
  ExploreFoodRoute: typeof ExploreFoodRoute
  ExploreHealthRoute: typeof ExploreHealthRoute
  ExploreHousingRoute: typeof ExploreHousingRoute
  ExploreLoneSoldierRoute: typeof ExploreLoneSoldierRoute
  ExploreMapsRoute: typeof ExploreMapsRoute
  ExploreMoneyPlannerRoute: typeof ExploreMoneyPlannerRoute
  ExploreReserveRoute: typeof ExploreReserveRoute
  ExploreRidesRoute: typeof ExploreRidesRoute
  ExploreShopsRoute: typeof ExploreShopsRoute
  ExploreTransitRoute: typeof ExploreTransitRoute
  ExploreUlpanRoute: typeof ExploreUlpanRoute
  ExploreUniRoute: typeof ExploreUniRoute
  ExploreUniFinderRoute: typeof ExploreUniFinderRoute
  ExploreVisaRoute: typeof ExploreVisaRoute
  GuidesIdRoute: typeof GuidesIdRoute
  JoinCodeRoute: typeof JoinCodeRoute
  ServicesInsuranceRoute: typeof ServicesInsuranceRoute
  ServicesOffersRoute: typeof ServicesOffersRoute
  SiddurIdRoute: typeof SiddurIdRoute
  SocialConversationIdRoute: typeof SocialConversationIdRoute
  BeforeYouFlyIndexRoute: typeof BeforeYouFlyIndexRoute
  BenefitsIndexRoute: typeof BenefitsIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  SiddurIndexRoute: typeof SiddurIndexRoute
  SocialIndexRoute: typeof SocialIndexRoute
  WhatsOnIndexRoute: typeof WhatsOnIndexRoute
  ApiAuthEmailWebhookRoute: typeof ApiAuthEmailWebhookRoute
  ExploreEventIdRoute: typeof ExploreEventIdRoute
  ExploreFitnessIdRoute: typeof ExploreFitnessIdRoute
  ExploreIdfUnitIdRoute: typeof ExploreIdfUnitIdRoute
  ExploreMapIdRoute: typeof ExploreMapIdRoute
  ExploreServiceIdRoute: typeof ExploreServiceIdRoute
  ServicesEsimPlanIdRoute: typeof ServicesEsimPlanIdRoute
  ServicesEsimMineRoute: typeof ServicesEsimMineRoute
  WhatsOnEventIdRoute: typeof WhatsOnEventIdRoute
  ExploreFitnessIndexRoute: typeof ExploreFitnessIndexRoute
  ExploreIdfIndexRoute: typeof ExploreIdfIndexRoute
  ExploreMapIndexRoute: typeof ExploreMapIndexRoute
  ServicesEsimIndexRoute: typeof ServicesEsimIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicWebhooksAirwallexRoute: typeof ApiPublicWebhooksAirwallexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/israel': {
      id: '/israel'
      path: '/israel'
      fullPath: '/israel'
      preLoaderRoute: typeof IsraelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money': {
      id: '/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof MoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme': {
      id: '/programme'
      path: '/programme'
      fullPath: '/programme'
      preLoaderRoute: typeof ProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reverify': {
      id: '/reverify'
      path: '/reverify'
      fullPath: '/reverify'
      preLoaderRoute: typeof ReverifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topup': {
      id: '/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof TopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/apps': {
      id: '/admin/apps'
      path: '/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof AdminAppsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/controls': {
      id: '/admin/controls'
      path: '/controls'
      fullPath: '/admin/controls'
      preLoaderRoute: typeof AdminControlsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/memberships': {
      id: '/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/money': {
      id: '/admin/money'
      path: '/money'
      fullPath: '/admin/money'
      preLoaderRoute: typeof AdminMoneyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/places': {
      id: '/admin/places'
      path: '/places'
      fullPath: '/admin/places'
      preLoaderRoute: typeof AdminPlacesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/programmes': {
      id: '/admin/programmes'
      path: '/programmes'
      fullPath: '/admin/programmes'
      preLoaderRoute: typeof AdminProgrammesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sim': {
      id: '/admin/sim'
      path: '/sim'
      fullPath: '/admin/sim'
      preLoaderRoute: typeof AdminSimRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/before-you-fly/': {
      id: '/before-you-fly/'
      path: '/before-you-fly'
      fullPath: '/before-you-fly/'
      preLoaderRoute: typeof BeforeYouFlyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/before-you-fly/esim': {
      id: '/before-you-fly/esim'
      path: '/before-you-fly/esim'
      fullPath: '/before-you-fly/esim'
      preLoaderRoute: typeof BeforeYouFlyEsimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/before-you-fly/insurance': {
      id: '/before-you-fly/insurance'
      path: '/before-you-fly/insurance'
      fullPath: '/before-you-fly/insurance'
      preLoaderRoute: typeof BeforeYouFlyInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits/': {
      id: '/benefits/'
      path: '/benefits'
      fullPath: '/benefits/'
      preLoaderRoute: typeof BenefitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits/$id': {
      id: '/benefits/$id'
      path: '/benefits/$id'
      fullPath: '/benefits/$id'
      preLoaderRoute: typeof BenefitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/army': {
      id: '/explore/army'
      path: '/explore/army'
      fullPath: '/explore/army'
      preLoaderRoute: typeof ExploreArmyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/budget': {
      id: '/explore/budget'
      path: '/explore/budget'
      fullPath: '/explore/budget'
      preLoaderRoute: typeof ExploreBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/community': {
      id: '/explore/community'
      path: '/explore/community'
      fullPath: '/explore/community'
      preLoaderRoute: typeof ExploreCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/cost-of-living': {
      id: '/explore/cost-of-living'
      path: '/explore/cost-of-living'
      fullPath: '/explore/cost-of-living'
      preLoaderRoute: typeof ExploreCostOfLivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/documents': {
      id: '/explore/documents'
      path: '/explore/documents'
      fullPath: '/explore/documents'
      preLoaderRoute: typeof ExploreDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/events': {
      id: '/explore/events'
      path: '/explore/events'
      fullPath: '/explore/events'
      preLoaderRoute: typeof ExploreEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/food': {
      id: '/explore/food'
      path: '/explore/food'
      fullPath: '/explore/food'
      preLoaderRoute: typeof ExploreFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/health': {
      id: '/explore/health'
      path: '/explore/health'
      fullPath: '/explore/health'
      preLoaderRoute: typeof ExploreHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/housing': {
      id: '/explore/housing'
      path: '/explore/housing'
      fullPath: '/explore/housing'
      preLoaderRoute: typeof ExploreHousingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/lone-soldier': {
      id: '/explore/lone-soldier'
      path: '/explore/lone-soldier'
      fullPath: '/explore/lone-soldier'
      preLoaderRoute: typeof ExploreLoneSoldierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/maps': {
      id: '/explore/maps'
      path: '/explore/maps'
      fullPath: '/explore/maps'
      preLoaderRoute: typeof ExploreMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/money-planner': {
      id: '/explore/money-planner'
      path: '/explore/money-planner'
      fullPath: '/explore/money-planner'
      preLoaderRoute: typeof ExploreMoneyPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/reserve': {
      id: '/explore/reserve'
      path: '/explore/reserve'
      fullPath: '/explore/reserve'
      preLoaderRoute: typeof ExploreReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/rides': {
      id: '/explore/rides'
      path: '/explore/rides'
      fullPath: '/explore/rides'
      preLoaderRoute: typeof ExploreRidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/shops': {
      id: '/explore/shops'
      path: '/explore/shops'
      fullPath: '/explore/shops'
      preLoaderRoute: typeof ExploreShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/transit': {
      id: '/explore/transit'
      path: '/explore/transit'
      fullPath: '/explore/transit'
      preLoaderRoute: typeof ExploreTransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/ulpan': {
      id: '/explore/ulpan'
      path: '/explore/ulpan'
      fullPath: '/explore/ulpan'
      preLoaderRoute: typeof ExploreUlpanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/uni': {
      id: '/explore/uni'
      path: '/explore/uni'
      fullPath: '/explore/uni'
      preLoaderRoute: typeof ExploreUniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/uni-finder': {
      id: '/explore/uni-finder'
      path: '/explore/uni-finder'
      fullPath: '/explore/uni-finder'
      preLoaderRoute: typeof ExploreUniFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/visa': {
      id: '/explore/visa'
      path: '/explore/visa'
      fullPath: '/explore/visa'
      preLoaderRoute: typeof ExploreVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$id': {
      id: '/guides/$id'
      path: '/guides/$id'
      fullPath: '/guides/$id'
      preLoaderRoute: typeof GuidesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme/': {
      id: '/programme/'
      path: '/'
      fullPath: '/programme/'
      preLoaderRoute: typeof ProgrammeIndexRouteImport
      parentRoute: typeof ProgrammeRoute
    }
    '/programme/inbox': {
      id: '/programme/inbox'
      path: '/inbox'
      fullPath: '/programme/inbox'
      preLoaderRoute: typeof ProgrammeInboxRouteImport
      parentRoute: typeof ProgrammeRoute
    }
    '/programme/info': {
      id: '/programme/info'
      path: '/info'
      fullPath: '/programme/info'
      preLoaderRoute: typeof ProgrammeInfoRouteImport
      parentRoute: typeof ProgrammeRoute
    }
    '/programme/schedule': {
      id: '/programme/schedule'
      path: '/schedule'
      fullPath: '/programme/schedule'
      preLoaderRoute: typeof ProgrammeScheduleRouteImport
      parentRoute: typeof ProgrammeRoute
    }
    '/programme/staff': {
      id: '/programme/staff'
      path: '/staff'
      fullPath: '/programme/staff'
      preLoaderRoute: typeof ProgrammeStaffRouteImport
      parentRoute: typeof ProgrammeRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/insurance': {
      id: '/services/insurance'
      path: '/services/insurance'
      fullPath: '/services/insurance'
      preLoaderRoute: typeof ServicesInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/offers': {
      id: '/services/offers'
      path: '/services/offers'
      fullPath: '/services/offers'
      preLoaderRoute: typeof ServicesOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siddur/': {
      id: '/siddur/'
      path: '/siddur'
      fullPath: '/siddur/'
      preLoaderRoute: typeof SiddurIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siddur/$id': {
      id: '/siddur/$id'
      path: '/siddur/$id'
      fullPath: '/siddur/$id'
      preLoaderRoute: typeof SiddurIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/': {
      id: '/social/'
      path: '/social'
      fullPath: '/social/'
      preLoaderRoute: typeof SocialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/$conversationId': {
      id: '/social/$conversationId'
      path: '/social/$conversationId'
      fullPath: '/social/$conversationId'
      preLoaderRoute: typeof SocialConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/calendar': {
      id: '/staff/calendar'
      path: '/calendar'
      fullPath: '/staff/calendar'
      preLoaderRoute: typeof StaffCalendarRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/communications': {
      id: '/staff/communications'
      path: '/communications'
      fullPath: '/staff/communications'
      preLoaderRoute: typeof StaffCommunicationsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/content': {
      id: '/staff/content'
      path: '/content'
      fullPath: '/staff/content'
      preLoaderRoute: typeof StaffContentRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/onboarding': {
      id: '/staff/onboarding'
      path: '/onboarding'
      fullPath: '/staff/onboarding'
      preLoaderRoute: typeof StaffOnboardingRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/overview': {
      id: '/staff/overview'
      path: '/overview'
      fullPath: '/staff/overview'
      preLoaderRoute: typeof StaffOverviewRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/settings': {
      id: '/staff/settings'
      path: '/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/team': {
      id: '/staff/team'
      path: '/team'
      fullPath: '/staff/team'
      preLoaderRoute: typeof StaffTeamRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/whats-on/': {
      id: '/whats-on/'
      path: '/whats-on'
      fullPath: '/whats-on/'
      preLoaderRoute: typeof WhatsOnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/email-webhook': {
      id: '/api/auth/email-webhook'
      path: '/api/auth/email-webhook'
      fullPath: '/api/auth/email-webhook'
      preLoaderRoute: typeof ApiAuthEmailWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/event/$id': {
      id: '/explore/event/$id'
      path: '/explore/event/$id'
      fullPath: '/explore/event/$id'
      preLoaderRoute: typeof ExploreEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/fitness/': {
      id: '/explore/fitness/'
      path: '/explore/fitness'
      fullPath: '/explore/fitness/'
      preLoaderRoute: typeof ExploreFitnessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/fitness/$id': {
      id: '/explore/fitness/$id'
      path: '/explore/fitness/$id'
      fullPath: '/explore/fitness/$id'
      preLoaderRoute: typeof ExploreFitnessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/idf/': {
      id: '/explore/idf/'
      path: '/explore/idf'
      fullPath: '/explore/idf/'
      preLoaderRoute: typeof ExploreIdfIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/idf/$unitId': {
      id: '/explore/idf/$unitId'
      path: '/explore/idf/$unitId'
      fullPath: '/explore/idf/$unitId'
      preLoaderRoute: typeof ExploreIdfUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/map/': {
      id: '/explore/map/'
      path: '/explore/map'
      fullPath: '/explore/map/'
      preLoaderRoute: typeof ExploreMapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/map/$id': {
      id: '/explore/map/$id'
      path: '/explore/map/$id'
      fullPath: '/explore/map/$id'
      preLoaderRoute: typeof ExploreMapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/service/$id': {
      id: '/explore/service/$id'
      path: '/explore/service/$id'
      fullPath: '/explore/service/$id'
      preLoaderRoute: typeof ExploreServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/esim/': {
      id: '/services/esim/'
      path: '/services/esim'
      fullPath: '/services/esim/'
      preLoaderRoute: typeof ServicesEsimIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/esim/$planId': {
      id: '/services/esim/$planId'
      path: '/services/esim/$planId'
      fullPath: '/services/esim/$planId'
      preLoaderRoute: typeof ServicesEsimPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/esim/mine': {
      id: '/services/esim/mine'
      path: '/services/esim/mine'
      fullPath: '/services/esim/mine'
      preLoaderRoute: typeof ServicesEsimMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/students/': {
      id: '/staff/students/'
      path: '/students'
      fullPath: '/staff/students/'
      preLoaderRoute: typeof StaffStudentsIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/students/$studentId': {
      id: '/staff/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/staff/students/$studentId'
      preLoaderRoute: typeof StaffStudentsStudentIdRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/whats-on/event/$id': {
      id: '/whats-on/event/$id'
      path: '/whats-on/event/$id'
      fullPath: '/whats-on/event/$id'
      preLoaderRoute: typeof WhatsOnEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/airwallex': {
      id: '/api/public/webhooks/airwallex'
      path: '/api/public/webhooks/airwallex'
      fullPath: '/api/public/webhooks/airwallex'
      preLoaderRoute: typeof ApiPublicWebhooksAirwallexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminAppsRoute: typeof AdminAppsRoute
  AdminControlsRoute: typeof AdminControlsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminMembershipsRoute: typeof AdminMembershipsRoute
  AdminMoneyRoute: typeof AdminMoneyRoute
  AdminPlacesRoute: typeof AdminPlacesRoute
  AdminProgrammesRoute: typeof AdminProgrammesRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminSimRoute: typeof AdminSimRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminAppsRoute: AdminAppsRoute,
  AdminControlsRoute: AdminControlsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminMembershipsRoute: AdminMembershipsRoute,
  AdminMoneyRoute: AdminMoneyRoute,
  AdminPlacesRoute: AdminPlacesRoute,
  AdminProgrammesRoute: AdminProgrammesRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminSimRoute: AdminSimRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffCalendarRoute: typeof StaffCalendarRoute
  StaffCommunicationsRoute: typeof StaffCommunicationsRoute
  StaffContentRoute: typeof StaffContentRoute
  StaffOnboardingRoute: typeof StaffOnboardingRoute
  StaffOverviewRoute: typeof StaffOverviewRoute
  StaffSettingsRoute: typeof StaffSettingsRoute
  StaffTeamRoute: typeof StaffTeamRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffStudentsStudentIdRoute: typeof StaffStudentsStudentIdRoute
  StaffStudentsIndexRoute: typeof StaffStudentsIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffCalendarRoute: StaffCalendarRoute,
  StaffCommunicationsRoute: StaffCommunicationsRoute,
  StaffContentRoute: StaffContentRoute,
  StaffOnboardingRoute: StaffOnboardingRoute,
  StaffOverviewRoute: StaffOverviewRoute,
  StaffSettingsRoute: StaffSettingsRoute,
  StaffTeamRoute: StaffTeamRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffStudentsStudentIdRoute: StaffStudentsStudentIdRoute,
  StaffStudentsIndexRoute: StaffStudentsIndexRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

interface ProgrammeRouteChildren {
  ProgrammeInboxRoute: typeof ProgrammeInboxRoute
  ProgrammeInfoRoute: typeof ProgrammeInfoRoute
  ProgrammeScheduleRoute: typeof ProgrammeScheduleRoute
  ProgrammeStaffRoute: typeof ProgrammeStaffRoute
  ProgrammeIndexRoute: typeof ProgrammeIndexRoute
}

const ProgrammeRouteChildren: ProgrammeRouteChildren = {
  ProgrammeInboxRoute: ProgrammeInboxRoute,
  ProgrammeInfoRoute: ProgrammeInfoRoute,
  ProgrammeScheduleRoute: ProgrammeScheduleRoute,
  ProgrammeStaffRoute: ProgrammeStaffRoute,
  ProgrammeIndexRoute: ProgrammeIndexRoute,
}

const ProgrammeRouteWithChildren = ProgrammeRoute._addFileChildren(
  ProgrammeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  ActivityRoute: ActivityRoute,
  AuthRoute: AuthRoute,
  CardRoute: CardRoute,
  ExchangeRoute: ExchangeRoute,
  HelpRoute: HelpRoute,
  IsraelRoute: IsraelRoute,
  MeRoute: MeRoute,
  MembershipRoute: MembershipRoute,
  MoneyRoute: MoneyRoute,
  NewsRoute: NewsRoute,
  PassportRoute: PassportRoute,
  ProgrammeRoute: ProgrammeRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ReverifyRoute: ReverifyRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TicketsRoute: TicketsRoute,
  TopupRoute: TopupRoute,
  VerifyRoute: VerifyRoute,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
  BeforeYouFlyEsimRoute: BeforeYouFlyEsimRoute,
  BeforeYouFlyInsuranceRoute: BeforeYouFlyInsuranceRoute,
  BenefitsIdRoute: BenefitsIdRoute,
  ExploreArmyRoute: ExploreArmyRoute,
  ExploreBudgetRoute: ExploreBudgetRoute,
  ExploreCommunityRoute: ExploreCommunityRoute,
  ExploreCostOfLivingRoute: ExploreCostOfLivingRoute,
  ExploreDocumentsRoute: ExploreDocumentsRoute,
  ExploreEventsRoute: ExploreEventsRoute,
  ExploreFoodRoute: ExploreFoodRoute,
  ExploreHealthRoute: ExploreHealthRoute,
  ExploreHousingRoute: ExploreHousingRoute,
  ExploreLoneSoldierRoute: ExploreLoneSoldierRoute,
  ExploreMapsRoute: ExploreMapsRoute,
  ExploreMoneyPlannerRoute: ExploreMoneyPlannerRoute,
  ExploreReserveRoute: ExploreReserveRoute,
  ExploreRidesRoute: ExploreRidesRoute,
  ExploreShopsRoute: ExploreShopsRoute,
  ExploreTransitRoute: ExploreTransitRoute,
  ExploreUlpanRoute: ExploreUlpanRoute,
  ExploreUniRoute: ExploreUniRoute,
  ExploreUniFinderRoute: ExploreUniFinderRoute,
  ExploreVisaRoute: ExploreVisaRoute,
  GuidesIdRoute: GuidesIdRoute,
  JoinCodeRoute: JoinCodeRoute,
  ServicesInsuranceRoute: ServicesInsuranceRoute,
  ServicesOffersRoute: ServicesOffersRoute,
  SiddurIdRoute: SiddurIdRoute,
  SocialConversationIdRoute: SocialConversationIdRoute,
  BeforeYouFlyIndexRoute: BeforeYouFlyIndexRoute,
  BenefitsIndexRoute: BenefitsIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  SiddurIndexRoute: SiddurIndexRoute,
  SocialIndexRoute: SocialIndexRoute,
  WhatsOnIndexRoute: WhatsOnIndexRoute,
  ApiAuthEmailWebhookRoute: ApiAuthEmailWebhookRoute,
  ExploreEventIdRoute: ExploreEventIdRoute,
  ExploreFitnessIdRoute: ExploreFitnessIdRoute,
  ExploreIdfUnitIdRoute: ExploreIdfUnitIdRoute,
  ExploreMapIdRoute: ExploreMapIdRoute,
  ExploreServiceIdRoute: ExploreServiceIdRoute,
  ServicesEsimPlanIdRoute: ServicesEsimPlanIdRoute,
  ServicesEsimMineRoute: ServicesEsimMineRoute,
  WhatsOnEventIdRoute: WhatsOnEventIdRoute,
  ExploreFitnessIndexRoute: ExploreFitnessIndexRoute,
  ExploreIdfIndexRoute: ExploreIdfIndexRoute,
  ExploreMapIndexRoute: ExploreMapIndexRoute,
  ServicesEsimIndexRoute: ServicesEsimIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicWebhooksAirwallexRoute: ApiPublicWebhooksAirwallexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
